- name: this playbook will install, configure as load balancer
  hosts: gateway
  become: yes
  tasks:
    - name: Install nginx webserver
      apt: name=nginx state=latest update_cache=yes
  
    - name: Congifure nginx web root folder
      copy: src=default-lb dest=/etc/nginx/nginx.conf

    - name: Restart the nginx web server
      command: service nginx restart
      

